# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-03 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0008_tales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Legends_and_traditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.UserProfile')),
            ],
        ),
    ]
