# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-03 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='legends_and_traditions',
            name='story',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='legends_and_traditions',
            name='title',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
