# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-03 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_auto_20161203_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legends_and_traditions',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
