# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-03 19:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0007_auto_20161203_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legends_and_traditions',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
