# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 23:12
from __future__ import unicode_literals

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gods',
            name='god_image',
            field=models.ImageField(blank=True, null=True),
        ),
    ]
