# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_gods_god_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gods',
            name='god_image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
