# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-03 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20160414_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('tale_image', models.ImageField(blank=True, null=True, upload_to='photos/')),
            ],
        ),
    ]
